// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "hyperpay_payment_sdk",
    platforms: [
        // HyperPay Mobile SDK 7.11.0 requires iOS 13.0
        // (OPPWAMobile.framework MinimumOSVersion).
        .iOS("13.0")
    ],
    products: [
        // The library name is hyphenated because Swift Package Manager uses it
        // as the CFBundleIdentifier when linked dynamically, and a
        // CFBundleIdentifier cannot contain underscores.
        .library(name: "hyperpay-payment-sdk", targets: ["hyperpay_payment_sdk"])
    ],
    dependencies: [
        // Vends Flutter.framework. Generated by the Flutter tool next to this
        // package when the app is built (Flutter 3.44 and later).
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        // HyperPay Mobile SDK 7.11.0 frameworks, vendored directly (Mastercard
        // 3DS certificate update, mandatory before 2026-07-07). OPPWAMobile
        // bundles its resources inside the framework, and ipworks3ds_sdk is the
        // production ("deploy") 3DS SDK that OPPWAMobile links against at
        // runtime, so it has to ship with the app even though the plugin never
        // imports it directly.
        .binaryTarget(
            name: "OPPWAMobile",
            path: "Frameworks/OPPWAMobile.xcframework"
        ),
        .binaryTarget(
            name: "ipworks3ds_sdk",
            path: "Frameworks/ipworks3ds_sdk.xcframework"
        ),
        .target(
            name: "hyperpay_payment_sdk",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "OPPWAMobile",
                "ipworks3ds_sdk"
            ]
        )
    ]
)
